config/routes.rb
Johnsonwebapps::Application.routes.draw do
  
  
  resources :users, :user_sessions
  	match 'login' => 'user_sessions#new', :as => :login
  	match 'logout' => 'user_sessions#destroy', :as => :logout
  
  resources :projects

  resources :abouts

  resources :contacts

  get "pages/contact"

  get "pages/about"

  resources :homes

end

app/models/about.rb
class About < ActiveRecord::Base
has_attached_file :photo,
     :styles => {
      # :thumb=> "100x100#",
      :thumb=> "100x100>",
       :small  => "400x400>" }
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  # GET /abouts
  # GET /abouts.xml
  def index
    @abouts = About.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @abouts }
    end
  end

  # GET /abouts/1
  # GET /abouts/1.xml
  def show
    @about = About.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @about }
    end
  end

  # GET /abouts/new
  # GET /abouts/new.xml
  def new
    @about = About.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @about }
    end
  end

  # GET /abouts/1/edit
  def edit
    @about = About.find(params[:id])
  end

  # POST /abouts
  # POST /abouts.xml
  def create
    @about = About.new(params[:about])

    respond_to do |format|
      if @about.save
        format.html { redirect_to(@about, :notice => 'About was successfully created.') }
        format.xml  { render :xml => @about, :status => :created, :location => @about }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @about.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /abouts/1
  # PUT /abouts/1.xml
  def update
    @about = About.find(params[:id])

    respond_to do |format|
      if @about.update_attributes(params[:about])
        format.html { redirect_to(@about, :notice => 'About was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @about.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /abouts/1
  # DELETE /abouts/1.xml
  def destroy
    @about = About.find(params[:id])
    @about.destroy

    respond_to do |format|
      format.html { redirect_to(abouts_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/views/abouts/_form.html.erb
<%= form_for @about, :html => { :multipart => true }  do |f| %>
  <% if @about.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@about.errors.count, "error") %> prohibited this about from being saved:</h2>

      <ul>
      <% @about.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<%= f.file_field :photo %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :main %><br />
    <%= f.text_area :main %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/abouts/edit.html.erb
<h1>Editing about</h1>

<%= render 'form' %>

<%= link_to 'Show', @about %> |
<%= link_to 'Back', abouts_path %>

app/views/abouts/index.html.erb
<h1>About Us</h1>

<% @abouts.each do |about| %>
<% if about.photo.exists? then %>
<%= image_tag about.photo.url(:thumb) %>
<% end %>
<h2><%= about.name %></h2>
<%= about.main %><br />
<!-- <%= link_to 'Show', about %> | -->
<% if current_user %>
<%= link_to 'Edit', edit_about_path(about) %> | <%= link_to 'Destroy', about, :confirm => 'Are you sure?', :method => :delete %>
<% end %>
 
<% end %>


<br />
<% if current_user %>
<%= link_to 'New About', new_about_path %>
<% end %>

app/views/abouts/new.html.erb
<h1>New about</h1>

<%= render 'form' %>

<%= link_to 'Back', abouts_path %>

app/views/abouts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @about.name %>
</p>

<p>
  <b>Main:</b>
  <%= @about.main %>
</p>


<%= link_to 'Edit', edit_about_path(@about) %> |
<%= link_to 'Back', abouts_path %>